version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/csharp-selenium-webdriver-sample"
    update_schedule: live

  - package_manager: "javascript"
    directory: "/typescript-selenium-webdriver-sample"
    update_schedule: live
    version_requirement_updates: increase_versions
