# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

pool:
    vmImage: windows-2019

variables:
  buildConfiguration: 'Release'
  solutionDirectory: '$(System.DefaultWorkingDirectory)/c#-selenium-webdriver-sample'
  outputDirectory: '$(solutionDirectory)/c#-selenium-webdriver-sample/bin/$(buildConfiguration)'

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.401'

- script: dotnet test --logger:trx
  displayName: dotnet test
  workingDirectory: $(solutionDirectory)

- task: PublishTestResults@2
  displayName: publish test results
  inputs:
      testResultsFiles: '**/TestResults/*.trx'
      testResultsFormat: VSTest
      searchFolder: $(solutionDirectory)
      testRunTitle: dotnet test
  condition: succeededOrFailed()

- publish: $(outputDirectory)
  displayName: publish drop
  name: drop