# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

pool:
    vmImage: windows-2019

variables:
  buildConfiguration: 'Release'
  projectDirectory: '$(System.DefaultWorkingDirectory)/c#-selenium-webdriver-sample'

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.401'

- task: NodeTool@0
  inputs:
    versionSpec: '10.16.2'
  displayName: use node 10.16.2

- script: dotnet test --logger:trx
  displayName: dotnet test
  workingDirectory: $(projectDirectory)

- task: PublishTestResults@2
  displayName: publish test results
  inputs:
      testResultsFiles: '**/TestResults/*.trx'
      testResultsFormat: VSTest
      searchFolder: $(projectDirectory)
      testRunTitle: dotnet test
  condition: succeededOrFailed()